server:
  port: 7001

spring:
  profiles: eureka7001.com
eureka:
  instance:
    hostname: eureka7001.com
  client:
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/
    fetch-registry: false
    register-with-eureka: false
